-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 17:54:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aprendizaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aprendizaje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aprendizaje` (
  `idAprendizaje` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAprendizaje`))
ENGINE = InnoDB;
INSERT INTO Aprendizaje VALUES(1,"VISUAL");
INSERT INTO Aprendizaje VALUES(2,"KINESTESICO");
INSERT INTO Aprendizaje VALUES(3,"AUDITIVO");
-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL auto_increment,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(120) NOT NULL,
  `Telefono` VARCHAR(10) NULL,
  `Tipo` INT(2) NOT NULL DEFAULT 0,
  `Tutor` INT NULL,
  `Aprendizaje` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_Usuario_Usuario1`
    FOREIGN KEY (`Tutor`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Aprendizaje1`
    FOREIGN KEY (`Aprendizaje`)
    REFERENCES `mydb`.`Aprendizaje` (`idAprendizaje`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Materia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Materia` (
  `idMateria` INT NOT NULL,
  `NombreMateria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;
INSERT INTO Materia VALUES(1,"INTRODUCTION TO CRIPTOGRAPHY");
INSERT INTO Materia VALUES(2,"STATISTICAL TOOLS FOR DATA ANALYTICS");

-- -----------------------------------------------------
-- Table `mydb`.`Leccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Leccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Leccion` (
  `idLeccion` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Materia` INT NOT NULL,
  `Tipo` TINYINT NOT NULL,
  `Contenido` JSON NOT NULL,
  PRIMARY KEY (`idLeccion`, `Materia`, `Tipo`),
  CONSTRAINT `fk_Leccion_Materia`
    FOREIGN KEY (`Materia`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO Leccion VALUES(1,"0. Introduccion a la Estadistica", 1,1,'{"contenido":["La estadística se utiliza para la recolección, presentación, organización y análisis de datos, con la cual se pueden obtener conclusiones que nos permiten tomar decisiones basado en un análisis previo."]}');
INSERT INTO Leccion VALUES(2,"1. Estadística desctiptiva", 1,1,'{"contenido":["Cuando se examina un grupo a este se le conoce como población o universo mientras que, si se examina un grupo derivado del anterior, a este se le llama muestra."]}');
INSERT INTO Leccion VALUES(3,"1.1 Medidas de tendencia central para datos agrupados y no agrupados", 1, 1,
'{"contenido":[
"El promedio es un valor que tiende a encontrarse en el centro de los conjuntos de datos, al promedio también se le conoce como medidas de tendencia central.", 
"Las medidas de tendencia central más utilizadas son: la media, mediana, moda.", 
"MEDIA ARITMETICA",
"La media aritmética se considera la medida de localización más importante ya que nos proporciona una localización central en una muestra de datos, la forma en la que se representa depende de si son datos de una muestra o una población",
"ecuacion aqui",
"MEDIANA"
"De un conjunto de números ordenados de menor a mayor, se selecciona el valor central o valores centrales en caso de que sea un conjunto de datos par."
"MODA",
"La moda es el valor más frecuente de un conjunto de datos, puede no haber y puede que cuando hay no sea única."]}');
INSERT INTO Leccion VALUES(3,"1.2 Medidas de dispersión para datos agrupados y no agrupados", 1, 1,
'{"contenido":[
"Varianza",
"La variabilidad de un conjunto de datos relacionados o no.",
"ecuacion aqui",
"Desviación estándar",
"Medida útil para conocer la desviación de los datos respecto a la media, en las muestras de datos se suele usar N-1 en lugar de N ya que permite obtener una mejor aproximación de los datos.",
"ecuacion aqui",
]}');
INSERT INTO Leccion VALUES(1,"PRUEBA 2", 2,1,'{"contenido":"hola prueba"}');
-- -----------------------------------------------------
-- Table `mydb`.`Progreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Progreso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Progreso` (
  `idUsuario` INT NOT NULL,
  `idLeccion` INT NOT NULL,
  `idMateria` INT NOT NULL,
  `Leccion_Tipo` TINYINT NOT NULL,
  `Completado` TINYINT NOT NULL DEFAULT 0,
  `Puntaje` INT NULL,
  PRIMARY KEY (`idUsuario`, `idLeccion`, `idMateria`, `Leccion_Tipo`),
  CONSTRAINT `fk_Progreso_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Progreso_Leccion1`
    FOREIGN KEY (`idLeccion` , `idMateria` , `Leccion_Tipo`)
    REFERENCES `mydb`.`Leccion` (`idLeccion` , `Materia` , `Tipo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
