-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 17:54:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aprendizaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aprendizaje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aprendizaje` (
  `idAprendizaje` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAprendizaje`))
ENGINE = InnoDB;

INSERT INTO Aprendizaje VALUES(1,"VISUAL");
INSERT INTO Aprendizaje VALUES(2,"KINESTESICO");
INSERT INTO Aprendizaje VALUES(3,"AUDITIVO");

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL auto_increment,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(10) NULL,
  `Tipo` INT(2) NOT NULL DEFAULT 0,
  `Tutor` INT NULL,
  `Tutorado` INT NULL,
  `Aprendizaje` INT NOT NULL,
  `Reputacion` INT NOT NULL default 1000,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_Usuario_Usuario1`
    FOREIGN KEY (`Tutor`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Aprendizaje1`
    FOREIGN KEY (`Aprendizaje`)
    REFERENCES `mydb`.`Aprendizaje` (`idAprendizaje`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Materia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Materia` (
  `idMateria` INT NOT NULL,
  `NombreMateria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;

INSERT INTO Materia VALUES(1,"STATISTICAL TOOLS FOR DATA ANALYTICS");
INSERT INTO Materia VALUES(2,"INTRODUCTION TO CRIPTOGRAPHY");



-- -----------------------------------------------------
-- Table `mydb`.`Leccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Leccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Leccion` (
  `idLeccion` INT NOT NULL,
  `Titulo` VARCHAR(100) NOT NULL,
  `Materia` INT NOT NULL,
  `Tipo` TINYINT NOT NULL,
  `Contenido` JSON NOT NULL,
  PRIMARY KEY (`idLeccion`, `Materia`, `Tipo`),
  CONSTRAINT `fk_Leccion_Materia`
    FOREIGN KEY (`Materia`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Progreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Progreso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Progreso` (
  `idUsuario` INT NOT NULL,
  `idLeccion` INT NOT NULL,
  `idMateria` INT NOT NULL,
  `Leccion_Tipo` TINYINT NOT NULL, -- 0 Teorico, 1 Ejercicico
  `Completado` TINYINT NOT NULL DEFAULT 0,
  `Puntaje` INT NULL,
  `Rendimiento` INT(2), -- 0 Requiere apoyo, 1 NO requiere apoyo, 2 Puede dar apoyo
  PRIMARY KEY (`idUsuario`, `idLeccion`, `idMateria`, `Leccion_Tipo`),
  CONSTRAINT `fk_Progreso_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Progreso_Leccion1`
    FOREIGN KEY (`idLeccion` , `idMateria` , `Leccion_Tipo`)
    REFERENCES `mydb`.`Leccion` (`idLeccion` , `Materia` , `Tipo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
